{
 "name":"momok-agent-1",
 "version":"1.1.0",
 "protocolVersion":"2025-06-18",
 "description":"AI-powered Web3 analytics and arbitrage monitoring",
 "transport":"streamable-http",
 "methods":["POST"],
 "capabilities":{
  "tools":true,
  "prompts":true,
  "resources":true
 },
 "tools":[
  "scan_arbitrage",
  "simulate_flashloan",
  "optimize_route",
  "detect_honeypot",
  "analyze_contract",
  "market_analysis"
 ],
 "prompts":[
  "find_arbitrage_opportunity",
  "risk_analysis"
 ],
 "status":"healthy"
}
